defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/clojure:lein-2.7.1

deps: &deps
  run: |
    curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | sudo python
    pip install awscli --upgrade --user

    sudo apt-get update
    sudo apt-get install make

restore_cache: &restore_cache
  restore_cache:
    key: project-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{checksum "project.clj" }}

save_cache: &save_cache
  save_cache:
    paths:
      - ~/.m2
    key: project-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{checksum "project.clj" }}

build: &build
  run: |
    cd ~/project && make jar SNAPSHOTS_BUCKET=$SNAPSHOTS_BUCKET

deploy: &deploy
  run: |
    cd ~/project && make SNAPSHOTS_BUCKET=$SNAPSHOTS_BUCKET

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *deps
      - *restore_cache
      - *build
      - *save_cache
      - *deploy

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: troywest-aws
